# Generated by Django 3.2.5 on 2021-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210715_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default='blank', max_length=500, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.ManyToManyField(default='blank', to='home.Answer'),
        ),
        migrations.AlterField(
            model_name='data',
            name='question',
            field=models.ManyToManyField(default='blank', to='home.Question'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tag',
            field=models.ManyToManyField(default='blank', to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='blank', max_length=500, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='blank', max_length=50, verbose_name='Data Tag'),
        ),
    ]
