# Generated by Django 3.2.5 on 2021-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210715_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.ManyToManyField(to='home.Answer'),
        ),
        migrations.AlterField(
            model_name='data',
            name='question',
            field=models.ManyToManyField(to='home.Question'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tag',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
