# Generated by Django 3.2.5 on 2021-07-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210716_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Index'),
        ),
    ]
