# Generated by Django 3.2.5 on 2021-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_messageexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Index'),
        ),
    ]
