# Generated by Django 3.2.5 on 2021-07-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_message_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-index']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-index']},
        ),
    ]
